export const productsData = [
    {
        id: 1,
        sku: 60904084923883030,
        title: "Lorem ipsum dolor sit amet",
        quantity: 1,
        description: "man tie dye cinza grey",
        availablrSizes: ["X", "L", "XL", "XXL"],
        price: 10,
        isFreeShipping: true,
    },
    {
        id: 2,
        sku: 609098084923883030,
        title: "consectetuer adipiscing elit",
        quantity: 1,
        description: "an tie dye cinza grey",
        availablrSizes: ["XS", "M", "L"],
        price: 14.9,
        isFreeShipping: true,
    },
    {
        id: 3,
        sku: 897684923883030,
        title: "iriure dolor in hendrerit in vulputate",
        quantity: 1,
        description: "n tie dye cinza grey",
        availablrSizes: ["X", "XXL"],
        price: 17,
        isFreeShipping: true,
    },
    {
        id: 4,
        sku: 868684923883030,
        title: "ullamcorper suscipit lobortis nisl",
        quantity: 1,
        description: " tie dye cinza grey",
        availablrSizes: ["X", "L", "XL"],
        price: 30,
        isFreeShipping: true,
    },
    {
        id: 5,
        sku: 1399971883030,
        title: "volutpat. Ut wisi enim ad",
        quantity: 1,
        description: " dye cinza grey",
        availablrSizes: ["L", "XXL"],
        price: 34.9,
        isFreeShipping: true,
    },
    {
        id: 6,
        sku: 6667553883030,
        title: "suscipit lobortis nisl ut aliquip",
        quantity: 1,
        description: "cinza man tie dye cinza grey",
        availablrSizes: ["X", "XL", "XXL"],
        price: 28,
        isFreeShipping: true,
    },
    {
        id: 7,
        sku: 609055566883030,
        title: "duis dolore te feugait nulla",
        quantity: 1,
        description: "man tie dye cinza grey",
        availablrSizes: ["X", "S", "XXL"],
        price: 14.6,
        isFreeShipping: true,
    },
    {
        id: 8,
        sku: 5747300923883030,
        title: "nostrud exerci tation ullamcorper",
        quantity: 1,
        description: "man tie dye cinza grey",
        availablrSizes: ["X", "L", "XL"],
        price: 67.9,
        isFreeShipping: true,
    },
    {
        id: 9,
        sku: 4357776923883030,
        title: "blandit praesent luptatum",
        quantity: 1,
        description: "man tie dye cinza grey",
        availablrSizes: ["X", "XXL"],
        price: 23.8,
        isFreeShipping: true,
    },
    {
        id: 10,
        sku: 26787984923883030,
        title: "et iusto odio dignissim qui blandit",
        quantity: 1,
        description: "man tie dye cinza grey",
        availablrSizes: ["XXL"],
        price: 34.8,
        isFreeShipping: true,
    },
]